# Generated by Django 5.1.1 on 2025-05-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
