# Generated by Django 5.1.1 on 2025-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbchat', '0004_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
