# Generated by Django 5.1.1 on 2025-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbchat', '0005_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
